### ISSUE TITLE
Cannot fetching any information

### ISSUE THREAD

**Issue by Naim120** [anishgowda21/Music-downloader-bot#2]
When giving a song, this is showing:

Hey there was an error while processing the media

HTTPConnectionPool(host='172.31.35.110', port=5000): Max retries exceeded with url: /song/?query=https://www.saavn.com/s/song/hindi/Satyameva-Jayate/Paniyon-Sa/OiAgWxB8Tmw?referrer=svn_source=share&svn_medium=org.telegram.plus&utm_source=share&utm_medium=org.telegram.plus&lyrics=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0dbda94b20>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by anishgowda21** [comment]
Try it again, it's  working fine for me .May be you spammed the bot with too many requests
